package vista.panel;

import javax.swing.JLabel;

public class PanelDeInicio extends javax.swing.JPanel {

    
    public PanelDeInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblConexion = new javax.swing.JLabel();

        setLayout(new java.awt.GridBagLayout());

        lblConexion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConexion.setText("Conectando...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(20, 20, 20, 20);
        add(lblConexion, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    public JLabel getLblConexion() {
        return lblConexion;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblConexion;
    // End of variables declaration//GEN-END:variables
}
