package vista.panel;

import controlador.ControladorPrincipal;
import javax.swing.ButtonGroup;
import javax.swing.JButton;
import javax.swing.JLabel;

public class PanelPrincipal extends javax.swing.JPanel {

    private final ControladorPrincipal controlador;
    private int tabla;

    public PanelPrincipal(ControladorPrincipal controlador) {
        initComponents();

        this.controlador = controlador;

        jtbGroupTablas.add(jtbArtistas);
        jtbGroupTablas.add(jtbEventos);
        jtbGroupTablas.add(jtbActuaciones);
        jtbGroupTablas.add(jtbUsuarios);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jtbGroupTablas = new javax.swing.ButtonGroup();
        lblTablas = new javax.swing.JLabel();
        jtbArtistas = new javax.swing.JToggleButton();
        jtbEventos = new javax.swing.JToggleButton();
        jtbActuaciones = new javax.swing.JToggleButton();
        jtbUsuarios = new javax.swing.JToggleButton();
        lblMetodos = new javax.swing.JLabel();
        btnGet = new javax.swing.JButton();
        btnPost = new javax.swing.JButton();
        btnPut = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();

        setLayout(new java.awt.GridBagLayout());

        lblTablas.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTablas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTablas.setText("TABLAS");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lblTablas, gridBagConstraints);

        jtbArtistas.setText("ARTISTAS");
        jtbArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbArtistasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jtbArtistas, gridBagConstraints);

        jtbEventos.setText("EVENTOS");
        jtbEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbEventosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jtbEventos, gridBagConstraints);

        jtbActuaciones.setText("ACTUACIONES");
        jtbActuaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbActuacionesActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jtbActuaciones, gridBagConstraints);

        jtbUsuarios.setText("USUARIOS");
        jtbUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtbUsuariosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(jtbUsuarios, gridBagConstraints);

        lblMetodos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblMetodos.setText("MÉTODOS HTTP");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(lblMetodos, gridBagConstraints);

        btnGet.setText("GET");
        btnGet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(btnGet, gridBagConstraints);

        btnPost.setText("POST");
        btnPost.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(btnPost, gridBagConstraints);

        btnPut.setText("PUT");
        btnPut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPutActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(btnPut, gridBagConstraints);

        btnDel.setText("DELETE");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        add(btnDel, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jtbArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbArtistasActionPerformed
        controlador.mostrarMetodos();
        btnPut.setEnabled(true);
        tabla = controlador.OPCION_ARTISTA;
    }//GEN-LAST:event_jtbArtistasActionPerformed

    private void jtbEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbEventosActionPerformed
        controlador.mostrarMetodos();
        btnPut.setEnabled(true);
        tabla = controlador.OPCION_EVENTO;
    }//GEN-LAST:event_jtbEventosActionPerformed

    private void jtbActuacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbActuacionesActionPerformed
        controlador.mostrarMetodos();
        btnPut.setEnabled(false);
        tabla = controlador.OPCION_ACTUACION;
    }//GEN-LAST:event_jtbActuacionesActionPerformed

    private void btnGetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetActionPerformed
        controlador.lanzarDialog(tabla, "GET");
    }//GEN-LAST:event_btnGetActionPerformed

    private void btnPostActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostActionPerformed
        controlador.lanzarDialog(tabla, "POST");
    }//GEN-LAST:event_btnPostActionPerformed

    private void btnPutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPutActionPerformed
        controlador.lanzarDialog(tabla, "PUT");
    }//GEN-LAST:event_btnPutActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        controlador.lanzarDialog(tabla, "DELETE");
    }//GEN-LAST:event_btnDelActionPerformed

    private void jtbUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtbUsuariosActionPerformed
        controlador.mostrarMetodos();
        btnPut.setEnabled(true);
        tabla = controlador.OPCION_USUARIO;
    }//GEN-LAST:event_jtbUsuariosActionPerformed

    public JButton getBtnDel() {
        return btnDel;
    }

    public JButton getBtnGet() {
        return btnGet;
    }

    public JButton getBtnPost() {
        return btnPost;
    }

    public JButton getBtnPut() {
        return btnPut;
    }

    public JLabel getLblMetodos() {
        return lblMetodos;
    }

    public ButtonGroup getJtbGroupTablas() {
        return jtbGroupTablas;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnGet;
    private javax.swing.JButton btnPost;
    private javax.swing.JButton btnPut;
    private javax.swing.JToggleButton jtbActuaciones;
    private javax.swing.JToggleButton jtbArtistas;
    private javax.swing.JToggleButton jtbEventos;
    private javax.swing.ButtonGroup jtbGroupTablas;
    private javax.swing.JToggleButton jtbUsuarios;
    private javax.swing.JLabel lblMetodos;
    private javax.swing.JLabel lblTablas;
    // End of variables declaration//GEN-END:variables
}
