package vista;

import controlador.ControladorPrincipal;
import java.awt.Cursor;
import java.awt.Insets;
import javax.swing.Box;
import javax.swing.JButton;
import javax.swing.JMenu;

public class Ventana extends javax.swing.JFrame {

    public Ventana(ControladorPrincipal controlador) {
        initComponents();

        menuInformes = new JButton("Informes");
        menuOpciones = new JButton("Opciones de conexión");
        menuLookAndFeel = new JMenu("Cambiar Look and Feel");
        menuSalir = new JButton("Salir");

        darEstiloDeMenu(menuInformes);
        darEstiloDeMenu(menuOpciones);
        darEstiloDeMenu(menuSalir);

        menuInformes.setMargin(new Insets(0, 5, 0, 0));
        menuSalir.setMargin(new Insets(0, 0, 0, 5));

        barraMenu.add(menuInformes);
        barraMenu.add(menuOpciones);
        barraMenu.add(menuLookAndFeel);
        barraMenu.add(Box.createHorizontalGlue());
        barraMenu.add(menuSalir);
        
        menuOpciones.addActionListener(e -> {
            controlador.lanzarDialogOpciones();
        });

        menuInformes.addActionListener(e -> {
            controlador.lanzarDialogInformes();
        });
        
        menuSalir.addActionListener(e -> {
            System.exit(0);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        barraMenu = new javax.swing.JMenuBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión BD");
        setResizable(false);

        barraMenu.setOpaque(true);
        setJMenuBar(barraMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 299, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JMenu getMenuLookAndFeel() {
        return menuLookAndFeel;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar barraMenu;
    // End of variables declaration//GEN-END:variables

    private final JButton menuInformes;
    private final JButton menuOpciones;
    private final JMenu menuLookAndFeel;
    private final JButton menuSalir;

    private void darEstiloDeMenu(JButton button) {
        button.setContentAreaFilled(false);
        button.setBorderPainted(false);
        button.setFocusPainted(false);

        button.setOpaque(false);

        button.setRolloverEnabled(true);

        button.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
}
