package vista.dialog;

import controlador.ControladorPrincipal;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

public class DialogResultadoGet extends javax.swing.JDialog {

    private final ControladorPrincipal controlador;

    public DialogResultadoGet(java.awt.Frame parent, boolean modal, ControladorPrincipal controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblResultadoNombre = new javax.swing.JLabel();
        txtFldResultadoNombre = new javax.swing.JTextField();
        lblResultadoDescLugarHash = new javax.swing.JLabel();
        lblResultadoFechaSalt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultadoDescLugarHash = new javax.swing.JTextArea();
        txtFldResultadoFechaSalt = new javax.swing.JTextField();
        lblResultadoImagen = new javax.swing.JLabel();
        lblResultadoIcono = new javax.swing.JLabel();
        btnResultadoImagen = new javax.swing.JButton();
        btnResultadoIcono = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblResultadoNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblResultadoNombre, gridBagConstraints);

        txtFldResultadoNombre.setEditable(false);
        txtFldResultadoNombre.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtFldResultadoNombre, gridBagConstraints);

        lblResultadoDescLugarHash.setText("Descripción |  Lugar | Hash");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblResultadoDescLugarHash, gridBagConstraints);

        lblResultadoFechaSalt.setText("Fecha | Salt");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblResultadoFechaSalt, gridBagConstraints);

        txtAreaResultadoDescLugarHash.setEditable(false);
        txtAreaResultadoDescLugarHash.setColumns(15);
        txtAreaResultadoDescLugarHash.setLineWrap(true);
        txtAreaResultadoDescLugarHash.setRows(5);
        txtAreaResultadoDescLugarHash.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtAreaResultadoDescLugarHash);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        txtFldResultadoFechaSalt.setEditable(false);
        txtFldResultadoFechaSalt.setColumns(15);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtFldResultadoFechaSalt, gridBagConstraints);

        lblResultadoImagen.setText("Imagen");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblResultadoImagen, gridBagConstraints);

        lblResultadoIcono.setText("Icono");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblResultadoIcono, gridBagConstraints);

        btnResultadoImagen.setText("Ver");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 21, 10, 21);
        getContentPane().add(btnResultadoImagen, gridBagConstraints);

        btnResultadoIcono.setText("Ver");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 21, 10, 21);
        getContentPane().add(btnResultadoIcono, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public JButton getBtnResultadoIcono() {
        return btnResultadoIcono;
    }

    public JButton getBtnResultadoImagen() {
        return btnResultadoImagen;
    }

    public JLabel getLblResultadoDescLugarHash() {
        return lblResultadoDescLugarHash;
    }

    public JLabel getLblResultadoFechaSalt() {
        return lblResultadoFechaSalt;
    }

    public JLabel getLblResultadoIcono() {
        return lblResultadoIcono;
    }

    public JLabel getLblResultadoImagen() {
        return lblResultadoImagen;
    }

    public JLabel getLblResultadoNombre() {
        return lblResultadoNombre;
    }

    public JTextArea getTxtAreaResultadoDescLugarHash() {
        return txtAreaResultadoDescLugarHash;
    }

    public JTextField getTxtFldResultadoFechaSalt() {
        return txtFldResultadoFechaSalt;
    }

    public JTextField getTxtFldResultadoNombre() {
        return txtFldResultadoNombre;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResultadoIcono;
    private javax.swing.JButton btnResultadoImagen;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblResultadoDescLugarHash;
    private javax.swing.JLabel lblResultadoFechaSalt;
    private javax.swing.JLabel lblResultadoIcono;
    private javax.swing.JLabel lblResultadoImagen;
    private javax.swing.JLabel lblResultadoNombre;
    private javax.swing.JTextArea txtAreaResultadoDescLugarHash;
    private javax.swing.JTextField txtFldResultadoFechaSalt;
    private javax.swing.JTextField txtFldResultadoNombre;
    // End of variables declaration//GEN-END:variables
}
