package vista.dialog;

import controlador.ControladorPrincipal;
import javax.swing.JCheckBox;
import javax.swing.JPasswordField;
import javax.swing.JTextField;

public class DialogUsuario extends javax.swing.JDialog {

    private final String metodoHttp;
    private final ControladorPrincipal controlador;

    public DialogUsuario(java.awt.Frame parent, boolean modal, String metodoHttp, ControladorPrincipal controlador) {
        super(parent, modal);
        initComponents();
        this.metodoHttp = metodoHttp;
        this.controlador = controlador;
        esconderComponentes();
    }

    private void esconderComponentes() {
        switch (metodoHttp) {
            case "GET", "DELETE" -> {
                lblUsuarioId.setText(lblUsuarioId.getText() + " (*)");

                lblUsuarioNombre.setVisible(false);
                txtFldUsuarioNombre.setVisible(false);
                lblUsuarioPwd.setVisible(false);
                pwdFldContrasenha.setVisible(false);
                lblUsuarioRol.setVisible(false);
                cbUsuarioAdmin.setVisible(false);
            }
            case "POST" -> {
                lblUsuarioNombre.setText(lblUsuarioNombre.getText() + " (*)");
                lblUsuarioPwd.setText(lblUsuarioPwd.getText() + " (*)");

                lblUsuarioId.setVisible(false);
                txtFldUsuarioId.setVisible(false);
            }
            case "PUT" -> {
                lblUsuarioId.setText(lblUsuarioId.getText() + " (*)");
                lblUsuarioNombre.setText(lblUsuarioNombre.getText() + " (*)");
                lblUsuarioPwd.setText(lblUsuarioPwd.getText() + " (*)");
            }
        }
        btnMetodo.setText(metodoHttp);
        pack();
    }

    public JCheckBox getCbUsuarioAdmin() {
        return cbUsuarioAdmin;
    }

    public JTextField getTxtFldUsuarioId() {
        return txtFldUsuarioId;
    }

    public JTextField getTxtFldUsuarioNombre() {
        return txtFldUsuarioNombre;
    }

    public JPasswordField getPwdFldContrasenha() {
        return pwdFldContrasenha;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblUsuarioId = new javax.swing.JLabel();
        lblUsuarioNombre = new javax.swing.JLabel();
        lblUsuarioPwd = new javax.swing.JLabel();
        lblUsuarioRol = new javax.swing.JLabel();
        btnMetodo = new javax.swing.JButton();
        txtFldUsuarioId = new javax.swing.JTextField();
        txtFldUsuarioNombre = new javax.swing.JTextField();
        cbUsuarioAdmin = new javax.swing.JCheckBox();
        pwdFldContrasenha = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión Usuario");
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblUsuarioId.setText("ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblUsuarioId, gridBagConstraints);

        lblUsuarioNombre.setText("Nombre");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblUsuarioNombre, gridBagConstraints);

        lblUsuarioPwd.setText("Contraseña");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblUsuarioPwd, gridBagConstraints);

        lblUsuarioRol.setText("Admin");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblUsuarioRol, gridBagConstraints);

        btnMetodo.setText("METODO");
        btnMetodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMetodoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 25, 10, 25);
        getContentPane().add(btnMetodo, gridBagConstraints);

        txtFldUsuarioId.setColumns(3);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtFldUsuarioId, gridBagConstraints);

        txtFldUsuarioNombre.setColumns(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtFldUsuarioNombre, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(cbUsuarioAdmin, gridBagConstraints);

        pwdFldContrasenha.setColumns(8);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(pwdFldContrasenha, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnMetodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMetodoActionPerformed
        switch (metodoHttp) {
            case "GET" ->
                controlador.get(this, controlador.OPCION_USUARIO);
            case "POST" ->
                controlador.post(this, controlador.OPCION_USUARIO);
            case "PUT" ->
                controlador.put(this, controlador.OPCION_USUARIO);
            default ->
                controlador.delete(this, controlador.OPCION_USUARIO);
        }
    }//GEN-LAST:event_btnMetodoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMetodo;
    private javax.swing.JCheckBox cbUsuarioAdmin;
    private javax.swing.JLabel lblUsuarioId;
    private javax.swing.JLabel lblUsuarioNombre;
    private javax.swing.JLabel lblUsuarioPwd;
    private javax.swing.JLabel lblUsuarioRol;
    private javax.swing.JPasswordField pwdFldContrasenha;
    private javax.swing.JTextField txtFldUsuarioId;
    private javax.swing.JTextField txtFldUsuarioNombre;
    // End of variables declaration//GEN-END:variables
}
