package vista.dialog;

import com.toedter.calendar.JDateChooser;
import controlador.ControladorInformes;
import javax.swing.JLabel;
import javax.swing.JTextField;

public class DialogInformes extends javax.swing.JDialog {

    private ControladorInformes controlador;

    public DialogInformes(java.awt.Frame parent, boolean modal, ControladorInformes controlador) {
        super(parent, modal);
        initComponents();
        this.controlador = controlador;
        this.lblGenerando.setVisible(false);
        pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lblInforme1 = new javax.swing.JLabel();
        lblInforme2 = new javax.swing.JLabel();
        btnInformeArtistas = new javax.swing.JButton();
        btnInformeEventos = new javax.swing.JButton();
        lblInforme3 = new javax.swing.JLabel();
        lblInforme4 = new javax.swing.JLabel();
        btnInformeEventoRango = new javax.swing.JButton();
        btnInformeEventosArtista = new javax.swing.JButton();
        txtFldInformeId = new javax.swing.JTextField();
        jdcFechaIni = new com.toedter.calendar.JDateChooser();
        jdcFechaFin = new com.toedter.calendar.JDateChooser();
        lblGenerando = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informes");
        getContentPane().setLayout(new java.awt.GridBagLayout());

        lblInforme1.setText("Datos de artistas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblInforme1, gridBagConstraints);

        lblInforme2.setText("Datos de eventos");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblInforme2, gridBagConstraints);

        btnInformeArtistas.setText("Generar informe");
        btnInformeArtistas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeArtistasActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnInformeArtistas, gridBagConstraints);

        btnInformeEventos.setText("Generar informe");
        btnInformeEventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeEventosActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnInformeEventos, gridBagConstraints);

        lblInforme3.setText("Eventos entre dos fechas");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 5);
        getContentPane().add(lblInforme3, gridBagConstraints);

        lblInforme4.setText("Eventos de artista con ID:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 0);
        getContentPane().add(lblInforme4, gridBagConstraints);

        btnInformeEventoRango.setText("Generar informe");
        btnInformeEventoRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeEventoRangoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnInformeEventoRango, gridBagConstraints);

        btnInformeEventosArtista.setText("Generar informe");
        btnInformeEventosArtista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformeEventosArtistaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(btnInformeEventosArtista, gridBagConstraints);

        txtFldInformeId.setColumns(10);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(txtFldInformeId, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        getContentPane().add(jdcFechaIni, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        getContentPane().add(jdcFechaFin, gridBagConstraints);

        lblGenerando.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblGenerando.setText("Generando informe...");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        getContentPane().add(lblGenerando, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInformeArtistasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeArtistasActionPerformed
        lblGenerando.setVisible(true);
        pack();
        controlador.generarInforme(controlador.CONSULTA_BASICA_ARTISTAS);
    }//GEN-LAST:event_btnInformeArtistasActionPerformed

    private void btnInformeEventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeEventosActionPerformed
        lblGenerando.setVisible(true);
        pack();
        controlador.generarInforme(controlador.CONSULTA_BASICA_EVENTOS);
    }//GEN-LAST:event_btnInformeEventosActionPerformed

    private void btnInformeEventoRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeEventoRangoActionPerformed
        lblGenerando.setVisible(true);
        pack();
        controlador.generarInforme(controlador.CONSULTA_EVENTOS_EN_RANGO);
    }//GEN-LAST:event_btnInformeEventoRangoActionPerformed

    private void btnInformeEventosArtistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformeEventosArtistaActionPerformed
        lblGenerando.setVisible(true);
        pack();
        controlador.generarInforme(controlador.CONSULTA_EVENTOS_DE_ARTISTA);
    }//GEN-LAST:event_btnInformeEventosArtistaActionPerformed

    public JDateChooser getJdcFechaFin() {
        return jdcFechaFin;
    }

    public JDateChooser getJdcFechaIni() {
        return jdcFechaIni;
    }

    public JTextField getTxtFldInformeId() {
        return txtFldInformeId;
    }

    public JLabel getLblGenerando() {
        return lblGenerando;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnInformeArtistas;
    private javax.swing.JButton btnInformeEventoRango;
    private javax.swing.JButton btnInformeEventos;
    private javax.swing.JButton btnInformeEventosArtista;
    private com.toedter.calendar.JDateChooser jdcFechaFin;
    private com.toedter.calendar.JDateChooser jdcFechaIni;
    private javax.swing.JLabel lblGenerando;
    private javax.swing.JLabel lblInforme1;
    private javax.swing.JLabel lblInforme2;
    private javax.swing.JLabel lblInforme3;
    private javax.swing.JLabel lblInforme4;
    private javax.swing.JTextField txtFldInformeId;
    // End of variables declaration//GEN-END:variables

}
